### ISSUE TITLE
SP4 Boot option display

### ISSUE THREAD

**Issue by Prince-of-Persia** [webbrandon/Surface-Boot-Themes#5]
After following the given instructions, the boot options are displayed in the middle of the screen! (where the line is in the surface picture)

**Comment by wolfy1339** [comment]
This is probably because this theme was designed for the 2 first Gens, and they had a screen resolution of 1920x1080. And the newer generations have a higher screen resolution.

**Comment by Prince-of-Persia** [comment]
So in `theme.txt` 

```
+ boot_menu {  
   left = 1250
   width = 550
   top = 350
height = 40%
... }
```

refers to the top left corner the the options?

**Comment by wolfy1339** [comment]
I'm not sure, but I would think so. Maybe look around on Google

**Comment by webbrandon** [comment]
I honestly remember very little about theming the GRUB2 ATM.  Instead of acting like I know what I am talking about I am refering you to the comprehensive guide https://drive.google.com/file/d/0B4ryPDYMqL_MNDgzNjYzMWEtMTIxZC00MzRkLTg1NWUtMmQzNTE0NTBjNDQ5/view

**Comment by wolfy1339** [comment]
I have found a newer edition (3rd vs 2nd) of the aforementioned guide: https://drive.google.com/file/d/0B4ryPDYMqL_MNDgzNjYzMWEtMTIxZC00MzRkLTg1NWUtMmQzNTE0NTBjNDQ5/view (Posted by the original author towheedm on Ubuntu Forums)

**Comment by wolfy1339** [comment]
I have found a more recent edition of the PDF document included in the archive: https://drive.google.com/file/d/0B82343FTJphIbElHUGVac1hBZnc/view
Unfortunately, I haven't yet found the whole archive yet

**Comment by peyton-chandarana** [comment]
I had this issue as well. I can confirm that by changing the values of "top" and "left" in theme.txt you can alter the position of the boot selection menu. The screen is 3000x2000 so my I set "left" to 2000 and top to "800". This gave me the expected result.
